lint: {}
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: PlasmoGenEpi
  description: This pipeline takes PMO format and provides key metrics on supplied
    markers applicable to drug resistance
  force: false
  is_nfcore: true
  name: plasmodiumdrugres
  org: nf-core
  outdir: .
  version: 1.0.0dev
