name: nf-core-pipeline-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.4.2 # R base version
  - r-dplyr # Add any R packages needed
  - r-optparse
  - r-ggplot2
  - r-tidyr
  - r-data.table
  - r-stringr
  - r-readr # Add the readr package
  - python=3.9 # Python version for compatibility
  - nextflow # Ensure Nextflow is available if testing locally
